name: "Issue Label Notifier"
description: "Notify individuals or teams based on issue labels."
inputs:
  edit_body:
    description: "Whether to edit the body to append `message` instead of posting a comment."
    required: false
  token:
    description: "The GitHub authentication token."
    required: false
    default: ${{ github.token }}
  recipients:
    description: "Mapping of label to notification recipients."
    required: true
  message:
    description: "The message to post in the issue comment."
    required: false
    default: 'Heads up {recipients} - the "{label}" label was applied to this issue.'
runs:
  using: "node16"
  main: "dist/index.js"

branding:
  icon: "bell"
  color: "gray-dark"
